In [1]:
import numpy as np
import pandas as pd

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score,f1_score, precision_score, recall_score, roc_auc_score

from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score, GridSearchCV

import pickle

from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier

In [2]:
#a

In [4]:
class uji(): 
    def __init__(self,data): 
        df0 = pd.read_csv('../data5/uji%snorm.csv'%data, delimiter= ",", header=None)
        df0=df0.fillna(0)
        self.com=df0[0]
        self.prot=df0[1282]
        self.x =df0.drop([0,1282], axis=1)
        df0[1300]=0
        
        self.y=df0[1300]
        self.dt=data
class latih(): 
    def __init__(self,data): 
        df = pd.read_csv("../data5/%s.csv"%data, delimiter=',')
        df.head()
        self.X = df.drop(['label'], axis=1)
        self.Y = df['label']
        self.dt=data
def dtuji(data): 
    return uji(data) 
def dtlatih(data): 
    return latih(data) 

dtf =dtuji('mbafika') #dtf.com, dtf.prot, dtf.x, dtf.y, dtf.dt
dtl =dtuji('mbalinda') #dtl.com, dtl.prot, dtl.x, dtl.y dtl.dt
dtt =dtuji('tambahan_2') #dtl.com, dtl.prot, dtl.x, dtl.y dtl.dt
df1= dtlatih('hasilsmote_spike30_1') #df1.X,df1.Y,df1.dt
df2= dtlatih('hasilsmote_spike30_2') #df2.X,df2.Y,df2.dt
df3= dtlatih('hasilsmote_spike30_3') #df3.X,df3.Y,df3.dt
df4= dtlatih('hasilsmote_spike30_4') #df4.X,df4.Y,df4.dt
df5= dtlatih('hasilsmote_spike30_5') #df5.X,df5.Y,df5.dt

In [5]:
dtg =dtuji('gabung') #dtl.com, dtl.prot, dtl.x, dtl.y dtl.dt

In [7]:
def load_model(model,o):
    rf = pickle.load(open('../data5/model/{0}_hasilsmote_spike30_{1}'.format(model,o), 'rb'))
#     print('{0}_hasilsmote_{1}'.format(model.__name__,o))
#     print('Best parameters found:', rf.best_params_)
#     print('AUC :',rf.cv_results_['mean_test_AUC'])
#     print('Accuracy :',rf.cv_results_['mean_test_Accuracy'])
#     print('F-measure :',rf.cv_results_['mean_test_F-measure'])
#     print('Precision :',rf.cv_results_['mean_test_Precision'])
#     print('Recall :',rf.cv_results_['mean_test_Recall'])
    return rf

In [8]:
def load_model2(model,o):
    rf = pickle.load(open('../data5/model/{0}_hasilsmote_spike30_{1}'.format(model,o), 'rb'))
    return rf

In [9]:

def prediksi(md,model,p,data,d):
    pred_x = pd.DataFrame(md.predict_proba(data.x))
    prob_x = pd.DataFrame(np.where(pred_x >= p, 1,0))
    print("threshold {0} ".format(p))
    print("{0}_hasilsmote_{1} ".format(model,d))
    print("hasil prediksi ",data.dt," : (0,1)")
    print(confusion_matrix(data.y, prob_x[1]))
    pred = pd.DataFrame(prob_x[1])
    pred=pred.drop([0])
    pred[2] = data.com
    pred[3] = data.prot
    #print(pred.head())
    #print(prob_x)
    pred[4] = pred_x[1]
    #print(pred.head())
    #print(pd.DataFrame(prob_x)[1].head())
    pred.to_excel('../data5/hasil_pred/{0}_{1}p_{2}_modelhasilsmote{3}.xlsx'.format(model,p,data.dt,d))

In [10]:
def pred3(model,p,datauji1,datauji2,datauji3,d):
    md=load_model(model,d)
    prediksi(md,model,p,datauji1,d)
    prediksi(md,model,p,datauji2,d)
    prediksi(md,model,p,datauji3,d)
def pred2(model,p,datauji1,datauji2,d):
    md=load_model(model,d)
    prediksi(md,model,p,datauji1,d)
    prediksi(md,model,p,datauji2,d)
def pred(model,p,datauji1,d):
    md=load_model(model,d)
    prediksi(md,model,p,datauji1,d)

In [11]:
pred3('mlp',0.5,dtf,dtl,dtt,2)
pred3('mlp',0.5,dtf,dtl,dtt,1)
pred3('mlp',0.5,dtf,dtl,dtt,3)
pred3('mlp',0.5,dtf,dtl,dtt,4)
pred3('mlp',0.5,dtf,dtl,dtt,5)

threshold 0.5 
mlp_hasilsmote_2 
hasil prediksi  mbafika  : (0,1)
[[127 113]
 [  0   0]]
threshold 0.5 
mlp_hasilsmote_2 
hasil prediksi  mbalinda  : (0,1)
[[1558 1490]
 [   0    0]]
threshold 0.5 
mlp_hasilsmote_2 
hasil prediksi  tambahan_2  : (0,1)
[[128 200]
 [  0   0]]
threshold 0.5 
mlp_hasilsmote_1 
hasil prediksi  mbafika  : (0,1)
[[148  92]
 [  0   0]]
threshold 0.5 
mlp_hasilsmote_1 
hasil prediksi  mbalinda  : (0,1)
[[1833 1215]
 [   0    0]]
threshold 0.5 
mlp_hasilsmote_1 
hasil prediksi  tambahan_2  : (0,1)
[[147 181]
 [  0   0]]
threshold 0.5 
mlp_hasilsmote_3 
hasil prediksi  mbafika  : (0,1)
[[142  98]
 [  0   0]]
threshold 0.5 
mlp_hasilsmote_3 
hasil prediksi  mbalinda  : (0,1)
[[1733 1315]
 [   0    0]]
threshold 0.5 
mlp_hasilsmote_3 
hasil prediksi  tambahan_2  : (0,1)
[[178 150]
 [  0   0]]
threshold 0.5 
mlp_hasilsmote_4 
hasil prediksi  mbafika  : (0,1)
[[122 118]
 [  0   0]]
threshold 0.5 
mlp_hasilsmote_4 
hasil prediksi  mbalinda  : (0,1)
[[1373 1675]
 [   0

In [29]:
pred('mlp',0.5,dtf,dtl,dtt,5)

TypeError: pred() takes 4 positional arguments but 6 were given

In [30]:
scoring = {'AUC': 'roc_auc', 'Accuracy': 'accuracy','F-measure':'f1','Precision':'precision', 'Recall':'recall'}


In [31]:
from sklearn import svm

In [39]:
pred3('svm_rbf',0.5,dtf,dtl,dtt,5)

threshold 0.5 
svm_rbf_hasilsmote_5 
hasil prediksi  mbafika  : (0,1)
[[240]]
threshold 0.5 
svm_rbf_hasilsmote_5 
hasil prediksi  mbalinda  : (0,1)
[[2941  107]
 [   0    0]]
threshold 0.5 
svm_rbf_hasilsmote_5 
hasil prediksi  tambahan_2  : (0,1)
[[156 172]
 [  0   0]]


In [15]:
pred3('svm_rbf',0.5,dtf,dtl,dtt,5)

threshold 0.5 
svm_rbf_hasilsmote_5 
hasil prediksi  mbafika  : (0,1)
[[240]]
threshold 0.5 
svm_rbf_hasilsmote_5 
hasil prediksi  mbalinda  : (0,1)
[[2904  144]
 [   0    0]]
threshold 0.5 
svm_rbf_hasilsmote_5 
hasil prediksi  tambahan_2  : (0,1)
[[ 89 239]
 [  0   0]]


In [12]:
pred3('svm_rbf',0.5,dtf,dtl,dtt,4)
pred3('svm_rbf',0.5,dtf,dtl,dtt,3)
pred3('svm_rbf',0.5,dtf,dtl,dtt,2)
pred3('svm_rbf',0.5,dtf,dtl,dtt,1)

threshold 0.5 
svm_rbf_hasilsmote_4 
hasil prediksi  mbafika  : (0,1)
[[199  41]
 [  0   0]]
threshold 0.5 
svm_rbf_hasilsmote_4 
hasil prediksi  mbalinda  : (0,1)
[[2297  751]
 [   0    0]]
threshold 0.5 
svm_rbf_hasilsmote_4 
hasil prediksi  tambahan_2  : (0,1)
[[163 165]
 [  0   0]]
threshold 0.5 
svm_rbf_hasilsmote_3 
hasil prediksi  mbafika  : (0,1)
[[240]]
threshold 0.5 
svm_rbf_hasilsmote_3 
hasil prediksi  mbalinda  : (0,1)
[[2923  125]
 [   0    0]]
threshold 0.5 
svm_rbf_hasilsmote_3 
hasil prediksi  tambahan_2  : (0,1)
[[ 89 239]
 [  0   0]]
threshold 0.5 
svm_rbf_hasilsmote_2 
hasil prediksi  mbafika  : (0,1)
[[202  38]
 [  0   0]]
threshold 0.5 
svm_rbf_hasilsmote_2 
hasil prediksi  mbalinda  : (0,1)
[[2316  732]
 [   0    0]]
threshold 0.5 
svm_rbf_hasilsmote_2 
hasil prediksi  tambahan_2  : (0,1)
[[157 171]
 [  0   0]]
threshold 0.5 
svm_rbf_hasilsmote_1 
hasil prediksi  mbafika  : (0,1)
[[240]]
threshold 0.5 
svm_rbf_hasilsmote_1 
hasil prediksi  mbalinda  : (0,1)
[[290

In [14]:
pred3('rf_spike30smote_100n_1000m',0.5,dtf,dtl,dtt,4)
pred3('rf_spike30smote_100n_1000m',0.5,dtf,dtl,dtt,3)
pred3('rf_spike30smote_100n_1000m',0.5,dtf,dtl,dtt,2)
pred3('rf_spike30smote_100n_1000m',0.5,dtf,dtl,dtt,1)
pred3('rf_spike30smote_100n_1000m',0.5,dtf,dtl,dtt,5)

threshold 0.5 
rf_spike30smote_100n_1000m_hasilsmote_4 
hasil prediksi  mbafika  : (0,1)
[[165  75]
 [  0   0]]
threshold 0.5 
rf_spike30smote_100n_1000m_hasilsmote_4 
hasil prediksi  mbalinda  : (0,1)
[[1902 1146]
 [   0    0]]
threshold 0.5 
rf_spike30smote_100n_1000m_hasilsmote_4 
hasil prediksi  tambahan_2  : (0,1)
[[105 223]
 [  0   0]]
threshold 0.5 
rf_spike30smote_100n_1000m_hasilsmote_3 
hasil prediksi  mbafika  : (0,1)
[[173  67]
 [  0   0]]
threshold 0.5 
rf_spike30smote_100n_1000m_hasilsmote_3 
hasil prediksi  mbalinda  : (0,1)
[[1861 1187]
 [   0    0]]
threshold 0.5 
rf_spike30smote_100n_1000m_hasilsmote_3 
hasil prediksi  tambahan_2  : (0,1)
[[ 46 282]
 [  0   0]]
threshold 0.5 
rf_spike30smote_100n_1000m_hasilsmote_2 
hasil prediksi  mbafika  : (0,1)
[[164  76]
 [  0   0]]
threshold 0.5 
rf_spike30smote_100n_1000m_hasilsmote_2 
hasil prediksi  mbalinda  : (0,1)
[[1945 1103]
 [   0    0]]
threshold 0.5 
rf_spike30smote_100n_1000m_hasilsmote_2 
hasil prediksi  tambahan_2 